name: build_the_webclient
on:
  push:
    branches: ["webclient"]
defaults:
  run:
    working-directory: prototype/webclient
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # alias v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # alias v3
        with:
          node-version: '14'
      - run: npm install
      - run: npm run generate_api
      - run: npm run build

